### ISSUE TITLE
Links on DockerHub README are broken

### ISSUE THREAD

**Issue by keithing** [civisanalytics/datascience-python#54]
In the current `README.md`, we use relative links.  This is nice, because as @stephen-hoover pointed out, the links are correct across branches and commits.  However, since these links are relative and we use the same `README.md` for Dockerhub as for Github, the links work on Github but not on Dockerhub.

**Comment by keithing** [comment]
Best solution here seems to be finding a workaround so that we can use a different README on DockerHub and GitHub.   If that's not feasible, I would favor fixing the links on DockerHub by using absolute links (meaning the README is more confusing on GitHub).  I favor this because my impression is that more users interact with datascience-python on DockerHub than interact with the README on specific branches on GitHub.

**Comment by stephen-hoover** [comment]
I suspect that you're correct about the best solution. I'm concerned that the documentation links could end up pointing at an old version of files (especially environment.yml). If we hardcode the master branch, then it may contain unreleased updates. We could hardcode a version tag, but that will require that maintainers remember to update that version tag in the README before each release. 

I rather like the idea of hardcoding a version-specific URL in the README links. It's not ideal, but it might be better than the alternatives.
