### ISSUE TITLE
Docker build fails due to missing package

### ISSUE THREAD

**Issue by shelbrudy** [civisanalytics/datascience-python#68]
Hi there!

I attempted to build this docker image locally and the build failed with the following error:

```Collecting package metadata: ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound:
  - openblas=0.3.5

The command '/bin/sh -c conda install -y boto &&     conda install -y nomkl &&     conda env update -f environment.yml -n root &&     conda clean --all -y &&     rm -rf ~/.cache/pip' returned a non-zero code: 1
```

This can be replicated by pulling down this repository and running `docker build -t datascience-python .`

**Comment by stephen-hoover** [comment]
It looks like openblas removed v0.3.5 from conda-forge because it doesn't work with SkylakeX CPUs (https://github.com/conda-forge/openblas-feedstock/issues/73). The most recent release looks like v0.3.6.
